"""Accuracy report -> ml/export/accuracy_report.md + accuracy_photos.png + accuracy_nyu.png
  python ml/accuracy_report.py [--ckpt ml/export/fastdepth_ft_128x96.pth]
Float = the PyTorch model (vendor checkpoint, or the fine-tuned one) at the export resolution; INT8 = ml/qmodel.py on model_q.json.
NYU = all readable images of the official 654-image test split that were downloaded (ml/data/val/official); photos = ml/data/photos (Wikimedia)."""
import argparse, glob, os, sys
import numpy as np
import torch
from PIL import Image
import cv2

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path[:0] = [HERE, os.path.join(ROOT, "host")]
import fd_common as C
from qmodel import QModel
from preprocess import resize_rgb

EXPORT = os.path.join(HERE, "export")


def tile(im, vmax, label):
    """RGB uint8 image or depth (metres) -> 256 x 192 BGR tile with a label; depth uses turbo with near = red"""
    if im.ndim == 3:
        t = cv2.cvtColor(np.asarray(im, np.uint8), cv2.COLOR_RGB2BGR)
    else:
        near = np.clip(255 * (1 - np.asarray(im, np.float64) / vmax), 0, 255).astype(np.uint8)
        t = cv2.applyColorMap(near, cv2.COLORMAP_TURBO)
        t[np.asarray(im) <= 0] = 0 if label == "ground truth" else t[np.asarray(im) <= 0]
    t = cv2.resize(t, (256, 192), interpolation=cv2.INTER_NEAREST)
    cv2.putText(t, label[:30], (4, 14), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (255, 255, 255), 1, cv2.LINE_AA)
    return t


def save_grid(rows, path):
    cv2.imwrite(path, np.vstack([np.hstack(r) for r in rows]))


def zero_fractions(qm, frames):
    """per NPU layer: fraction of input activation elements that are exactly 0 (what zero-skip can skip) for the shipped zero points,
    and for a variant re-quantised to zero point 0 (real 0 -> q 0, range 0..127, scale hi/127)"""
    rows = {}
    for rgb in frames:
        outs = qm.run(rgb)
        x0 = rgb.astype(np.int64) - 128
        for i, l in enumerate(qm.layers):
            if l["type"] not in ("conv", "pwconv"):
                continue
            j = l["inputs"][0]
            x = x0 if j == -2 else outs[j]
            zp = l["in_zp"]
            s_in = l["scales"]["s_in"]
            real = (x - zp) * s_in
            hi = s_in * 255
            q0 = np.clip(np.round(real / (hi / 127)), 0, 127)
            r = rows.setdefault(l["name"], [0, 0, 0])
            r[0] += int((x == 0).sum()); r[1] += int((q0 == 0).sum()); r[2] += x.size
    return {k: (v[0] / v[2], v[1] / v[2]) for k, v in rows.items()}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default=None)
    a = ap.parse_args()
    qm = QModel()
    W, H = qm.W, qm.H
    model = C.load_model()
    vendor = C.load_model()
    if a.ckpt:
        model.load_state_dict(torch.load(a.ckpt, map_location="cpu", weights_only=False)["model_state_dict"])
    files = C.nyu_files()
    res = {"vendor_224": [], "vendor_small": [], "float": [], "int8": []}
    gal = []
    for k, f in enumerate(files):
        r, d = C.load_raw(f)
        x224, g224 = C.prep(r, d, 224, 224)
        res["vendor_224"].append(C.metrics(C.float_forward(vendor, x224), g224))
        x, g = C.prep(r, d, W, H)
        res["vendor_small"].append(C.metrics(C.float_forward(vendor, x), g))
        pf = C.float_forward(model, x)
        res["float"].append(C.metrics(pf, g))
        pq = qm.depth_m(qm.run(x))
        res["int8"].append(C.metrics(pq, g))
        if k % 18 == 0 and len(gal) < 6:
            gal.append((x, g, pf, pq))
    M = {k: np.mean(np.array(v), axis=0) for k, v in res.items()}
    n = len(files)

    # photos
    photos = [(os.path.basename(p), resize_rgb(Image.open(p), W, H)) for p in sorted(glob.glob(os.path.join(HERE, "data", "photos", "*.jpg")))]
    vmax = qm.mq["output"]["max"] * 0.6
    rows = []
    for name, rgb in photos:
        pf = C.float_forward(model, rgb)
        pq = qm.depth_m(qm.run(rgb))
        rows.append([tile(rgb, vmax, name), tile(pf, vmax, "float"), tile(pq, vmax, "INT8 (golden model = board)")])
    save_grid(rows, os.path.join(EXPORT, "accuracy_photos.png"))
    save_grid([[tile(x, vmax, "NYU RGB"), tile(g, vmax, "ground truth"), tile(pf, vmax, "float"), tile(pq, vmax, "INT8")] for (x, g, pf, pq) in gal],
              os.path.join(EXPORT, "accuracy_nyu.png"))

    zf = zero_fractions(qm, [p[1] for p in photos[:4]] + [g[0] for g in gal[:4]])
    d = (M["int8"][0] - M["float"][0]) / M["float"][0] * 100
    L = [f"# Accuracy report - depth model ({qm.mq['model']})", "",
         f"Generated by `ml/accuracy_report.py`. Input {W}x{H} RGB (host resize), output depth in metres = "
         f"{qm.mq['output']['scale']:.5f} x (q + 128), max {qm.mq['output']['max']:.2f} m. Test set: {n} images of the official NYU Depth v2 "
         f"test split (val/official, the first part of the 654 that downloaded), val_transform geometry (resize 250x333, centre crop 228x304, resize). "
         f"Metrics per image, then averaged; pixels with ground truth > 1 mm.", "",
         "| Model | Input | RMSE (m) | mean abs rel | delta1 (<1.25) |", "|---|---|---|---|---|",
         f"| community FastDepth checkpoint, float | 224x224 | {M['vendor_224'][0]:.3f} | {M['vendor_224'][1]:.3f} | {M['vendor_224'][2]:.3f} |",
         f"| community FastDepth checkpoint, float | {W}x{H} | {M['vendor_small'][0]:.3f} | {M['vendor_small'][1]:.3f} | {M['vendor_small'][2]:.3f} |",
         f"| shipped model, float ({'trained at ' + str(W) + 'x' + str(H) + ': ' + os.path.basename(a.ckpt) if a.ckpt else 'vendor'}) | {W}x{H} | {M['float'][0]:.3f} | {M['float'][1]:.3f} | {M['float'][2]:.3f} |",
         f"| **shipped model, INT8 (integer golden model = board)** | {W}x{H} | **{M['int8'][0]:.3f}** | **{M['int8'][1]:.3f}** | **{M['int8'][2]:.3f}** |", "",
         f"INT8 vs float RMSE: {d:+.2f} % (target: within 5 %). Paper (official pruned weights, 224x224, all 654 images): RMSE 0.604 m, delta1 0.771.", "",
         "Images: `accuracy_nyu.png` (RGB | ground truth | float | INT8), `accuracy_photos.png` (10 Wikimedia Commons indoor photos, "
         "licences in ml/data/photos/LICENSES.md; web_04 is a 1927 painted advertisement, kept as an out-of-distribution example). Colour map turbo, near = red.", "",
         "## Zero fraction of the NPU layers' input activations (what ZERO_SKIP can skip)", "",
         "Shipped quantisation: every activation is a ReLU / ReLU6 output stored with zero point -128 (real 0 = q -128), so q == 0 is a mid-range value "
         "and the array's zero-skip almost never fires. The zero-point-0 variant (real 0 = q 0, range 0..127, i.e. one bit less resolution) "
         "would make the ReLU zeros skippable. Measured on 8 frames:", "",
         "| Layer | zeros, shipped (zp -128) | zeros, zp-0 variant |", "|---|---|---|"]
    for k, (a0, a1) in zf.items():
        L.append(f"| {k} | {a0 * 100:.1f} % | {a1 * 100:.1f} % |")
    L += ["", "MACs per layer: `macs.csv`."]
    open(os.path.join(EXPORT, "accuracy_report.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L[4:12]))


if __name__ == "__main__":
    main()
