"""model_q.json -> model_blob.bin (in the export dir) + fw/include/model_<name>.h (layer table, see fw/include/model.h)
(exact layout:"model_layers.h and model_blob.bin").   Run: python ml/export_c.py [export dir, default ml/export]
"""
import json, os, struct, sys, zlib
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TYPES = {"conv": 0, "pwconv": 1, "dwconv": 2, "upsample": 3, "add": 4, "lut": 5, "fc": 6, "maxpool": 7, "avgpool": 8, "flatten": 9, "relu": 10, "bilinear": 11}


def build_blob(layers):
    blob = bytearray()
    offs = []

    def put(arr_bytes):
        while len(blob) % 4:
            blob.append(0)
        o = len(blob)
        blob.extend(arr_bytes)
        return o

    for l in layers:
        o = dict(w_off=0, b_off=0, m_off=0, s_off=0, lut_off=0)
        if "W" in l:
            o["w_off"] = put(np.asarray(l["W"], dtype=np.int8).tobytes())
            o["b_off"] = put(np.asarray(l["bias"], dtype="<i4").tobytes())
            o["m_off"] = put(np.asarray(l["M"], dtype="<u2").tobytes())
            o["s_off"] = put(np.asarray(l["S"], dtype=np.uint8).tobytes())
        if "table" in l:
            o["lut_off"] = put(np.asarray(l["table"], dtype=np.int8).tobytes())
        offs.append(o)
    while len(blob) % 4:
        blob.append(0)
    return bytes(blob), offs


def main():
    exp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "export")
    mq = json.load(open(os.path.join(exp, "model_q.json")))
    L = mq["layers"]
    blob, offs = build_blob(L)
    crc = zlib.crc32(blob) & 0xFFFFFFFF
    open(os.path.join(exp, "model_blob.bin"), "wb").write(blob)

    rows = []
    max_act = 0
    for i, (l, o) in enumerate(zip(L, offs)):
        ins = l["inputs"]
        in_a = ins[0]
        in_b = ins[1] if len(ins) > 1 else 0
        pad = l.get("pad", [0, 0, 0, 0])
        max_act = max(max_act, l["out_H"] * l["out_W"] * l["C_out"])
        rows.append(
            f"    /* {i:2d} {l['name']:8s} */ {{ {TYPES[l['type']]}, {l['relu']}, {l['stride']}, {l['factor']}, "
            f"{l['KH']}, {l['KW']}, {l['C_in']}, {l['C_out']}, {l['in_H']}, {l['in_W']}, {l['out_H']}, {l['out_W']}, "
            f"{pad[0]}, {pad[1]}, {pad[2]}, {pad[3]}, {l['in_zp']}, {l['out_zp']}, {l.get('za', 0)}, {l.get('zb', 0)}, "
            f"{in_a}, {in_b}, {l.get('Ma', 0)}, {l.get('Mb', 0)}, {l.get('S_add', 0)}, "
            f"{l.get('align', 0)}, {l.get('pad_value', l['in_zp'])}, "
            f"{o['w_off']}u, {o['b_off']}u, {o['m_off']}u, {o['s_off']}u, {o['lut_off']}u }},")
    out = mq["output"]; pre = mq["preproc"]; gate = mq["gate"]
    assert (pre["width"], pre["height"], pre["channels"]) == (128, 96, 3) and (gate["canny_low"], gate["canny_high"]) == (40, 100), \
        "fw/include/model.h fixes the input size and the Canny gate for every model"
    name = os.path.basename(os.path.normpath(exp))
    name = "fastdepth" if name == "export" else name.replace("export_", "")
    N = name.upper()
    h = f"""/* model_{name}.h - GENERATED by ml/export_c.py from {os.path.relpath(exp, ROOT)}/model_q.json. Do not edit. Included by fw/src/models.c.
 * Model: {mq['model']}
 * Blob: {os.path.relpath(exp, ROOT)}/model_blob.bin, {len(blob)} bytes, CRC-32 0x{crc:08X}. Largest activation {max_act} B. */
#ifndef MODEL_{N}_H
#define MODEL_{N}_H
#include "model.h"

static const layer_desc_t LAYERS_{N}[{len(L)}] = {{
""" + "\n".join(rows) + f"""
}};

static const model_desc_t MODEL_DESC_{N} = {{
    "{mq.get('short_name', 'FastDepth (MobileNet + NNConv5)' if name == 'fastdepth' else name)}", LAYERS_{N}, {len(L)}, {len(blob)}u, 0x{crc:08X}u,
    {0 if out['type'] == 'depth' else 1}, {int(round(out['scale'] * 1e6))}, {out['zero_point']}
}};

#endif
"""
    open(os.path.join(ROOT, "fw", "include", f"model_{name}.h"), "w", newline="\n").write(h)
    # (the host tests read ml/export/model_blob.bin directly; the board receives the blob over UART)
    print(f"model_blob.bin {len(blob)} B, CRC-32 0x{crc:08X}, {len(L)} layers, largest activation {max_act} B")


if __name__ == "__main__":
    main()
