/* models.c - the models built into the firmware (layer tables generated by ml/export_c.py). Index = CMD_SET_MODEL argument. */
#include "model.h"
#include "model_fastdepth.h"
#include "model_midas.h"

const model_desc_t *const MODELS[N_MODELS] = { &MODEL_DESC_FASTDEPTH, &MODEL_DESC_MIDAS };
