"""Generate fw/tests/vec/vectors.h from the Python references (reference/qmath_ref.py rq, reference/canny_ref.py).
Run from the repo root:  python fw/tools/gen_fw_vectors.py     (the generated header is checked in; rerun when the references change)"""
import os, sys, random
import numpy as np
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
sys.path.insert(0, os.path.join(ROOT, "reference"))   # repo layout
sys.path.insert(0, ROOT)                              # reference files next to fw/
from qmath_ref import rq
from canny_ref import canny_ref

rnd = random.Random(2026)
out = ["/* GENERATED by fw/tools/gen_fw_vectors.py from reference/qmath_ref.py and reference/canny_ref.py - do not edit */",
       "#ifndef FW_VECTORS_H", "#define FW_VECTORS_H", "#include <stdint.h>", ""]

# --- rq vectors ---
n = 3000
rows = []
for i in range(n):
    M = rnd.choice([1, 32767, rnd.randint(1, 32767), rnd.randint(1, 64)])
    S = rnd.choice([0, 31, rnd.randint(0, 31), rnd.randint(8, 20)])
    acc = rnd.choice([0, -(1 << 31), (1 << 31) - 1, rnd.randint(-(1 << 31), (1 << 31) - 1), rnd.randint(-5000, 5000)])
    bias = rnd.choice([0, rnd.randint(-(1 << 20), 1 << 20), rnd.randint(-100, 100)])
    zp = rnd.choice([-128, 0, 127, rnd.randint(-128, 127)])
    relu = rnd.randint(0, 1)
    rows.append((acc, bias, M, S, zp, relu, rq(acc, bias, M, S, zp, relu)))
out.append(f"#define RQ_N {n}")
out.append("typedef struct { int32_t acc, bias; uint16_t M; uint8_t S; int8_t zp; uint8_t relu; int8_t expect; } rq_vec_t;")
out.append("static const rq_vec_t RQ_VEC[RQ_N] = {")
for r in rows:
    out.append("  {%d, %d, %d, %d, %d, %d, %d}," % (r[0] if r[0] != -(1 << 31) else -2147483647 - 1, r[1], r[2], r[3], r[4], r[5], r[6]))
out.append("};\n")

# --- canny frames ---
frames = []
r = np.random.default_rng(7)
f = np.zeros((20, 24), dtype=np.int64); f[5:15, 8:18] = 200; frames.append(("square", f, 40, 100))
yy, xx = np.mgrid[0:32, 0:32]; f = np.clip(np.where(xx > 14, 220, 25) + (r.integers(0, 30, (32, 32))), 0, 255); frames.append(("step_noise", f, 40, 100))
frames.append(("random17x23", r.integers(0, 256, (17, 23)), 20, 60))
frames.append(("random9x9", r.integers(0, 256, (9, 9)), 30, 90))
f = np.full((24, 24), 200); frames.append(("flat", f, 30, 80))
out.append("typedef struct { int H, W; uint8_t low, high; uint16_t score; const uint8_t *gray; const int8_t *edge; } canny_vec_t;")
names = []
for nm, g, lo, hi in frames:
    g = np.asarray(g, dtype=np.int64)
    e = canny_ref(g, lo, hi)
    H, W = g.shape
    out.append(f"static const uint8_t CG_{nm}[{H*W}] = {{" + ",".join(str(int(v)) for v in g.reshape(-1)) + "};")
    out.append(f"static const int8_t  CE_{nm}[{H*W}] = {{" + ",".join(str(int(v)) for v in e.reshape(-1)) + "};")
    score = 1000 * int((e != 0).sum()) // (H * W)
    names.append((nm, H, W, lo, hi, score))
out.append("#define CANNY_NV %d" % len(names))
out.append("static const canny_vec_t CANNY_VEC[CANNY_NV] = {")
for nm, H, W, lo, hi, score in names:
    out.append(f"  {{{H}, {W}, {lo}, {hi}, {score}, CG_{nm}, CE_{nm}}},")
out.append("};\n#endif")
p = os.path.join(ROOT, "fw", "tests", "vec", "vectors.h")
open(p, "w", newline="\n").write("\n".join(out) + "\n")
print("wrote", p, len(rows), "rq vectors,", len(names), "canny frames;", "edge counts:", [(n_, s) for n_, *_, s in names])
