/* depth.h - integer runtime for an exported depth network.
 * The layer table comes from fw/include/model.h (MODELS[], generated by ml/export_c.py); the weights live in the model's blob, which
 * the host streams to the board (WEIGHTS packets) - the runtime only gets a pointer to it. conv / pwconv run on the NPU (npu_matmul,
 * K tiles accumulated on chip, X replayed from the NPU's buffer) or on the CPU; dwconv, upsample, bilinear, relu and skip-add run on
 * the CPU. Every layer is bit-exact with ml/qmodel.py. */
#ifndef DEPTH_H
#define DEPTH_H
#include <stdint.h>
#include <stddef.h>
#include "npu.h"
#include "model.h"

typedef struct {
    const model_desc_t *m;
    const uint8_t *blob;                 /* the model's blob, 4-byte aligned */
    int8_t  *act[MAX_LAYERS];            /* output of every layer (INT8 HWC) */
    int8_t  *in;                         /* network input x = p - 128, H x W x 3 */
    int8_t  *scratch;                    /* im2col of the standard conv layers */
    npu_t   *npu;
    int      use_npu;                    /* 1: conv/pwconv on the NPU, 0: everything on the CPU */
    int      npu_errors;
    uint32_t t_layer_us[MAX_LAYERS];
    uint32_t t_npu_us, t_cpu_us;         /* time of the last run spent in NPU layers / CPU layers */
} depth_net_t;

size_t depth_mem_bytes(const model_desc_t *m);                   /* bytes needed for depth_init's `mem` */
void   depth_init(depth_net_t *d, const model_desc_t *m, const uint8_t *blob, uint8_t *mem, npu_t *npu);
int    depth_run(depth_net_t *d, const uint8_t *rgb);            /* rgb: PREPROC_H x PREPROC_W x 3 uint8; returns NPU error count */
const int8_t *depth_output(const depth_net_t *d);                /* final layer: PREPROC_H x PREPROC_W x 1 */
uint32_t depth_macs(const model_desc_t *m);                      /* MACs per frame (conv, pwconv, dwconv) */
#endif
