/* model.h - layer table format shared by every exported model, and the list of models built into the firmware.
 * The per-model tables (model_fastdepth.h, model_midas.h) are generated by ml/export_c.py; fw/src/models.c collects them in MODELS[].
 * The board holds the weights of every model at the same time (one DDR slot each, uploaded once); CMD_SET_MODEL picks the active one. */
#ifndef MODEL_H
#define MODEL_H
#include <stdint.h>

enum { L_CONV = 0, L_PWCONV = 1, L_DWCONV = 2, L_UPSAMPLE = 3, L_ADD = 4, L_LUT = 5, L_FC = 6, L_MAXPOOL = 7, L_AVGPOOL = 8, L_FLATTEN = 9,
       L_RELU = 10, L_BILINEAR = 11 };
typedef struct {
    uint8_t  type, relu, stride, factor;
    uint16_t kh, kw, cin, cout;
    uint16_t in_h, in_w, out_h, out_w;
    int8_t   pad_t, pad_l, pad_b, pad_r;
    int8_t   in_zp, out_zp, za, zb;
    int16_t  in_a, in_b;                          /* -2 = network input, >= 0 = that layer's output */
    uint16_t Ma, Mb;
    uint8_t  S_add;
    uint8_t  align;                               /* bilinear: 1 = align_corners */
    int8_t   pad_v;                               /* value of padded pixels (= in_zp except where the model pads with something else) */
    uint32_t w_off, b_off, m_off, s_off, lut_off; /* byte offsets into the model's blob */
} layer_desc_t;

typedef struct {
    const char         *name;
    const layer_desc_t *layers;
    int                 n_layers;
    uint32_t            blob_bytes, blob_crc32;
    uint8_t             out_kind;                 /* 0 depth (small = near), 1 disparity (large = near) */
    int32_t             out_scale_x1e6;           /* real units per output step x 10^6 (metres for depth) */
    int8_t              out_zp;
} model_desc_t;

/* every model takes the same input and gives a map of the same size */
#define PREPROC_W        128
#define PREPROC_H        96
#define PREPROC_C        3
#define GATE_CANNY_LOW   40
#define GATE_CANNY_HIGH  100

#define MAX_LAYERS       160
#define MODEL_FASTDEPTH  0
#define MODEL_MIDAS      1
#define N_MODELS         2
extern const model_desc_t *const MODELS[N_MODELS];

#endif
